from app.models import db, Asset

def seed_assets():
    asset1 = Asset(name= "Apple",
        symbol = "AAPL",
        description= "Apple, Inc. engages in the design, manufacture, and sale of smartphones, personal computers, tablets, wearables and accessories, and other variety of related services. It operates through the following geographical segments= Americas, Europe, Greater China, Japan, and Rest of Asia Pacific. The Americas segment includes North and South America. The Europe segment consists of European countries, as well as India, the Middle East, and Africa. The Greater China segment comprises of China, Hong Kong, and Taiwan. The Rest of Asia Pacific segment includes Australia and Asian countries. Its products and services include iPhone, Mac, iPad, AirPods, Apple TV, Apple Watch, Beats products, Apple Care, iCloud, digital content stores, streaming, and licensing services. The company was founded by Steven Paul Jobs, Ronald Gerald Wayne, and Stephen G. Wozniak on April 1, 1976 and is headquartered in Cupertino, CA.",
        ceo= "Timothy Donald Cook",
        employees= 137000,
        headquarters= "Cupertino, California",
        founded= 1976,
        market_cap= 1370000000000,
        price_earning_ratio= 24.12,
        dividend_yield= 1.07,
        average_volume= 43690000)

    asset2 = Asset(name= "Microsoft",
        symbol= "MSFT",
        description= "Microsoft Corp. engages in the development and support of software, services, devices, and solutions. It operates through the following business segments= Productivity and Business Processes; Intelligent Cloud; and More Personal Computing. The Productivity and Business Processes segment comprises products and services in the portfolio of productivity, communication, and information services of the company spanning a variety of devices and platform. The Intelligent Cloud segment refers to the public, private, and hybrid serve products and cloud services of the company which can power modern business. The More Personal Computing segment encompasses products and services geared towards the interests of end users, developers, and IT professionals across all devices. The firm also offers operating systems; cross-device productivity applications; server applications; business solution applications; desktop and server management tools; software development tools; video games; personal computers, tablets; gaming and entertainment consoles; other intelligent devices; and related accessories. The company was founded by Paul Gardner Allen and William Henry Gates III in 1975 and is headquartered in Redmond, WA.",
        ceo= "Satya Nadella",
        employees= 144000,
        headquarters= "Redmond, Washington",
        founded= 1975,
        market_cap= 1400000000000,
        price_earning_ratio= 30.50,
        dividend_yield= 1.11,
        average_volume= 39410000)
    asset3 = Asset(name= "Tesla",
        symbol= "TSLA",
        description= "Tesla, Inc. engages in the design, development, manufacture, and sale of fully electric vehicles, energy generation and storage systems. It also provides vehicle service centers, supercharger station, and self-driving capability. The company operates through the following segments= Automotive and Energy Generation and Storage. The Automotive segment includes the design, development, manufacture and sale of electric vehicles. The Energy Generation and Storage segment includes the design, manufacture, installation, sale, and lease of stationary energy storage products and solar energy systems, and sale of electricity generated by its solar energy systems to customers. It develops energy storage products for use in homes, commercial facilities and utility sites. The company was founded by Jeffrey B. Straubel, Elon Reeve Musk, Martin Eberhard, and Marc Tarpenning on July 1, 2003 and is headquartered in Palo Alto, CA.",
        ceo= "Elon Reeve Musk",
        employees= 48016,
        headquarters= "Palo Alto, California",
        founded= 2003,
        market_cap= 150820000000,
        price_earning_ratio= 0,
        dividend_yield= 0,
        average_volume= 18320000)

    asset4 =Asset(name= "Spotify",
        symbol= "SPOT",
        description= "Spotify Technology S.A., also called Spotify, is a digital music service offering music fans instant access to a world of music. The company operates through the following segments= Premium and Ad-Supported. The Premium segment provides subscribers with unlimited online and offline high-quality streaming access of music and podcasts on computers, tablets, and mobile devices, users can connect through speakers, receivers, televisions, cars, game consoles, and smart watches. It also offers a music listening experience without commercial breaks. The Ad-Supported segment provides users with limited on-demand online access of music and unlimited online access of podcasts on their computers, tablets, and compatible mobile devices. It also serves both premium subscriber acquisition channel and a robust option for users who are unable or unwilling to pay a monthly subscription fee but still want to enjoy access to a wide variety of high-quality audio content. The company was founded by Daniel Ek and Martin Lorentzon in April, 2006 and is headquartered in Luxembourg.",
        ceo= "Daniel Ek",
        employees= 0,
        headquarters= "Luxembourg, Luxembourg",
        founded= 2006,
        market_cap= 29510000000,
        price_earning_ratio= 0,
        dividend_yield= 0,
        average_volume= 1390000)

    asset5 = Asset(name= "General Electric",
        symbol= "GE",
        description= "General Electric Company, also called GE, is a technology and financial services company. It operates through the following segments= Power, Renewable Energy, Aviation, Healthcare, and Capital. The Power segment offers technologies, solutions, and services related to energy production, which includes gas and steam turbines, generators, and power generation services. The Renewable Energy segment provides wind turbine platforms, hardware & software, offshore wind turbines, solutions, products & services to hydropower industry, blades for onshore & offshore wind turbines, and high voltage equipment. The Aviation segment provides jet engines & turboprops for commercial airframes, maintenance, component repair, and overhaul services, as well as replacement parts, additive machines & materials, and engineering services. The Healthcare segment provides healthcare technologies in medical imaging, digital solutions, patient monitoring, and diagnostics, drug discovery, biopharmaceutical manufacturing technologies and performance enhancement solutions. The Capital segment leases & finances aircraft, aircraft engines and helicopters, and also provides financial and underwriting solutions. The company was founded by Thomas Alva Edison in 1878 and is headquartered in Boston, MA.",
        ceo= "H. Lawrence Culp",
        employees= 205000,
        headquarters= "Boston, Massachusetts",
        founded= 1878,
        market_cap= 54840000000,
        price_earning_ratio= 8.25,
        dividend_yield= 0.73,
        average_volume= 135800000)

    asset6 = Asset(name= "Amazon",
        symbol= "AMZN",
        description= "Amazon.com, Inc. engages in the provision of online retail shopping services. It operates through the following business segments= North America, International, and Amazon Web Services (AWS). The North America segment includes retail sales of consumer products and subscriptions through North America-focused websites such as www.amazon.com and www.amazon.ca. The International segment offers retail sales of consumer products and subscriptions through internationally-focused websites. The Amazon Web Services segment involves in the global sales of compute, storage, database, and AWS service offerings for start-ups, enterprises, government agencies, and academic institutions. The company was founded by Jeffrey P. Bezos in July 1994 and is headquartered in Seattle, WA.",
        ceo= "Jeffrey P. Bezos",
        employees= 798000,
        headquarters= "Seattle, Washington",
        founded= 1994,
        market_cap= 1210000000000,
        price_earning_ratio= 115.11,
        dividend_yield= 0,
        average_volume= 4660000)

    asset7 = Asset(name= "Disney",
        symbol= "DIS",
        description= "The Walt Disney Company, also called Disney, is a diversified international family entertainment and media enterprise. It operates through the following segments= Media Networks, Parks, Experiences and Products, Studio Entertainment and Direct-to-Consumer and International (DTCI). The Media Networks segment includes cable and broadcast television networks, television production and distribution operations, domestic television stations, radio networks and stations. The Parks, Experiences and Products segment owns and operates the Walt Disney World Resort in Florida; the Disneyland Resort in California; Aulani, a Disney Resort & Spa in Hawaii; the Disney Vacation Club; the Disney Cruise Line; and Adventures by Disney. The Studio Entertainment segment produces and acquires live-action and animated motion pictures, direct-to-video content, musical recordings and live stage plays. This segment distributes films primarily under the Walt Disney Pictures, Pixar, Marvel, Lucasfilm and Touchstone banners. The DTCI segment licenses the company's trade names, characters and visual and literary properties to various manufacturers, game developers, publishers and retailers throughout the world. It also develops and publishes games, primarily for mobile platforms, and books, magazines and comic books. This segment also distributes branded merchandise directly through retail, online and wholesale businesses. The Walt Disney was founded by Walter Elias Disney on October 16, 1923 and is headquartered in Burbank, CA.",
        ceo= "Robert Chapek",
        employees= 223000,
        headquarters= "Burbank, California",
        founded= 1923,
        market_cap= 211060000000,
        price_earning_ratio= 36.80,
        dividend_yield= 1.74,
        average_volume= 27030000)

    asset8 = Asset(name= "Starbucks",
        symbol= "SBUX",
        description= "Starbucks Corp. engages in the production, marketing, and retailing of specialty coffee. It operates through the following segments= Americas; China/Asia Pacific (CAP); Europe, Middle East, and Africa (EMEA); and Channel Development. The Americas, CAP, EMEA segments sells coffee and other beverages, complementary food, packaged coffees, single-serve coffee products, and a focused selection of merchandise through company-oriented stores, and licensed stores. The Channel Development segment include sales of packaged coffee, tea, and ready-to-drink beverages to customers outside of its company-operated and licensed stores. The company brands include Evolution Fresh, Teavana, Tazo Tea and Seattle's Best. Starbucks was founded by Jerry Baldwin and Howard D. Schultz on November 4, 1985 and is headquartered in Seattle, WA.",
        ceo= "Kevin R. Johnson",
        employees= 346000,
        headquarters= "Seattle, Washington",
        founded= 1985,
        market_cap= 89040000000,
        price_earning_ratio= 26.41,
        dividend_yield= 2.21,
        average_volume= 12570000)

    asset9 = Asset(name= "Zoom",
        symbol= "ZM",
        description= "Zoom Video Communications, Inc. engages in the provision of video-first communications platform. It connects people through frictionless video, voice, chat and content sharing, and enable face-to-face video experiences for thousands of people in a single meeting across disparate devices and locations. It focuses on customer and employee happiness, a video-first cloud architecture, recognized market leadership, viral demand, an efficient go-to-market strategy, and robust customer support. The company was founded by Eric S. Yuan in 2011 and is headquartered in San Jose, CA.",
        ceo= "Eric S. Yuan",
        employees= 2532,
        headquarters= "San Jose, California",
        founded= 2011,
        market_cap= 45950000000,
        price_earning_ratio= 2040,
        dividend_yield= 0,
        average_volume= 9550000)

    asset10 = Asset(name= "Facebook",
        symbol= "FB",
        description= "Facebook, Inc. operates as a social networking company worldwide. The company engages in the development of social media applications for people to connect through mobile devices, personal computers, and other surfaces. It enables users to share opinions, ideas, photos, videos, and other activities online. The firm's products include Facebook, Instagram, Messenger, WhatsApp, and Oculus. The company was founded by Mark Elliot Zuckerberg, Dustin Moskovitz, Chris R. Hughes, Andrew McCollum, and Eduardo P. Saverin on February 4, 2004 and is headquartered in Menlo Park, CA.",
        ceo= "Mark Elliot Zuckerberg",
        employees= 44942,
        headquarters= "Menlo Park, California",
        founded= 2004,
        market_cap= 607500000000,
        price_earning_ratio= 28.89,
        dividend_yield= 0,
        average_volume= 20510000)

    asset11 = Asset(name= "Home Depot",
        symbol= "HD",
        description= "The Home Depot, Inc. engages in the sale of building materials and home improvement products. Its products include building materials, home improvement products, lawn and garden products, and decor products. It offers home improvement installation services,and tool and equipment rental. The company was founded by Bernard Marcus, Arthur M. Blank, Kenneth Gerald Langone, and Pat Farrah on June 29, 1978 and is headquartered at Atlanta, GA.",
        ceo= "Craig A. Menear",
        employees= 415700,
        headquarters= "Atlants, Georgia",
        founded= 1978,
        market_cap= 263540000000,
        price_earning_ratio= 23.35,
        dividend_yield= 2.51,
        average_volume= 6240000)

    asset12 = Asset(name= "JPMorgan Chase",
        symbol= "JPM",
        description= "JPMorgan Chase & Co., also called JPMorgan Chase, is a financial holding company. It provides financial and investment banking services. The firm offers a range of investment banking products and services in all capital markets, including advising on corporate strategy and structure, capital raising in equity and debt markets, risk management, market making in cash securities and derivative instruments, and brokerage and research. It operates through the following segments= Consumer and Community Banking, Corporate and Investment Bank, Commercial Banking and Asset and Wealth Management. The Consumer and Community Banking segment serves consumers and businesses through personal service at bank branches and through automated teller machine, online, mobile, and telephone banking. The Corporate and Investment Bank segment offers a suite of investment banking, market-making, prime brokerage, and treasury and securities products and services to a global client base of corporations, investors, financial institutions, government and municipal entities. The Commercial Banking segment delivers services to U.S. and its multinational clients, including corporations, municipalities, financial institutions, and non profit entities. It also provides financing to real estate investors and owners as well as financial solutions, including lending, treasury services, investment banking, and asset management. The Asset and Wealth Management segment provides asset and wealth management services. The company was founded in 1968 and is headquartered in New York, NY.",
        ceo= "James Dimon",
        employees= 256981,
        headquarters= "New York, New York",
        founded= 1968,
        market_cap= 275600000000,
        price_earning_ratio= 9.70,
        dividend_yield= 4.19,
        average_volume= 26720000)

    asset13 = Asset(name= "Berkshire Hathaway",
        symbol= "BRK.B",
        description= "Berkshire Hathaway, Inc. provides property and casualty insurance and reinsurance, utilities and energy, freight rail transportation, finance, manufacturing, retailing, and services. It operates through following segments= GEICO, Berkshire Hathaway Reinsurance Group, Berkshire Hathaway Primary Group, Burlington Northern Santa Fe, LLC (BNSF), Berkshire Hathaway Energy, McLane Company, Manufacturing, and Service and Retailing. The GEICO segments involves in underwriting private passenger automobile insurance mainly by direct response methods. The Berkshire Hathaway Reinsurance Group segment consists of underwriting excess-of-loss and quota-share and facultative reinsurance worldwide. The Berkshire Hathaway Primary Group segment comprises of underwriting multiple lines of property and casualty insurance policies for primarily commercial accounts. The BNSF segment operates railroad systems in North America. The Berkshire Hathaway Energy segments deals with regulated electric and gas utility, including power generation and distribution activities, and real estate brokerage activities. The McLane Company segment offers wholesale distribution of groceries and non-food items. The Manufacturing segment includes industrial and end-user products, building products, and apparel. The Service and Retailing segment provides fractional aircraft ownership programs, aviation pilot training, electronic components distribution, and various retailing businesses, including automobile dealerships, and trailer and furniture leasing. The company was founded by Oliver Chace in 1839 and is headquartered in Omaha, NE.",
        ceo= "Warren Edward Buffett",
        employees= 391500,
        headquarters= "Omaha, Nebraska",
        founded= 1839,
        market_cap= 426370000000,
        price_earning_ratio= 42.38,
        dividend_yield= 0,
        average_volume= 8650000)

    asset14 = Asset(name= "Ford",
        symbol= "F",
        description= "Ford Motor Co. engages in the manufacture, distribution, and sale of automobiles. It operates through the following three segments= Automotive, Mobility, and Ford Credit. The Automotive segment engages in developing, manufacturing, marketing and servicing of Ford cars, Lincoln vehicles. The Mobility segment includes Ford Smart Mobility LLC and autonomous vehicles business. The Ford Credit segment comprises Ford Credit business on a consolidated basis, which is primarily vehicle-related financing and leasing activities. The company was founded by Henry Ford on June 16, 1903 and is headquartered in Dearborn, MI.",
        ceo= "James P. Hackett",
        employees= 190000,
        headquarters= "Detroit, Michigan",
        founded= 1903,
        market_cap= 21120000000,
        price_earning_ratio= 0,
        dividend_yield= 12.12,
        average_volume= 95660000)

    asset15 = Asset(name= "Merck",
        symbol= "MRK",
        description= "Merck & Co., Inc. engages in the provision of health solutions through its prescription medicines, vaccines, biologic therapies, animal health, and consumer care products. It operates through the following segments= Pharmaceutical, Animal Health, Healthcare Services, and Alliances. The Pharmaceutical segment includes human health pharmaceutical and vaccine products. The Animal Health segment discovers, develops, manufactures, and markets animal health products, such as pharmaceutical and vaccine products, for the prevention, treatment and control of disease in livestock and companion animal species. The Healthcare Services segment offers services and solutions that focus on engagement, health analytics, and clinical services to improve the value of care delivered to patients. The Alliances segment includes results from the company's relationship with AstraZeneca LP related to sales of Nexium and Prilosec. The company was founded in 1891 and is headquartered in Kenilworth, NJ.",
        ceo= "Kenneth C. Frazier",
        employees= 71000,
        headquarters= "Kenilworth, New Jersey",
        founded= 1891,
        market_cap= 201220000000,
        price_earning_ratio= 20.18,
        dividend_yield= 3.06,
        average_volume= 10640000)

    asset16 = Asset(name= "Boeing",
        symbol= "BA",
        description= "Boeing Company, also called Boeing, is an aerospace company, which engages in the manufacture of commercial jetliners and defense, space and security systems. It operates through the following segments= Commercial Airplanes; Defense, Space and Security; Global Services; and Boeing Capital. The Commercial Airplanes segment includes the development, production, and market of commercial jet aircraft and provides fleet support services, principally to the commercial airline industry worldwide. The Defense, Space and Security segment refers to the research, development, production and modification of manned and unmanned military aircraft and weapons systems for global strike, including fighter and combat rotorcraft aircraft and missile systems; global mobility, including tanker, rotorcraft and tilt-rotor aircraft; and airborne surveillance and reconnaissance, including command and control, battle management and airborne anti-submarine aircraft. The Global Services segment provides services to commercial and defense customers. The Boeing Capital segment seeks to ensure that Boeing customers have the financing they need to buy and take delivery of their Boeing product and manages overall financing exposure. The company was founded by William Edward Boeing on July 15, 1916 and is headquartered in Chicago, IL.",
        ceo= "David L. Calhoun",
        employees= 161100,
        headquarters= "Chicago, Illinois",
        founded= 1916,
        market_cap= 76430000000,
        price_earning_ratio= 0,
        dividend_yield= 6.44,
        average_volume= 31270000)

    asset17 = Asset(name= "Netflix",
        symbol= "NFLX",
        description= "Netflix, Inc. Common Stock, also called Netflix, is a streaming entertainment service company, which provides subscription service streaming movies and television episodes over the Internet and sending DVDs by mail. It operates through the following segments= Domestic Streaming, International Streaming and Domestic DVD. The Domestic Streaming segment derives revenues from monthly membership fees for services consisting solely of streaming content to its members in the United States. The International Streaming segment includes fees from members outside the United States. The Domestic DVD segment covers revenues from services consisting solely of DVD-by-mail. The company was founded by Marc Randolph and Wilmot Reed Hastings Jr., on August 29, 1997 and is headquartered in Los Gatos, CA.",
        ceo= "Wilmot Reed Hastings",
        employees= 8600,
        headquarters= "Los Gatos, California",
        founded= 1997,
        market_cap= 198050000000,
        price_earning_ratio= 91.93,
        dividend_yield= 0,
        average_volume= 7310000)

    asset18 = Asset(name= "Twitter",
        symbol= "TWTR",
        description= "Twitter, Inc., also called Twitter, is a global platform for public self-expression and conversation in real time. It provides a network that connects users to people, information, ideas, opinions, and news. The company's services include live commentary, live connections and live conversations. Its application provides social networking services and micro-blogging services through mobile devices and the Internet. The company can also be used as a marketing tool for businesses. It's products and services include Twitter, Periscope, Promoted Tweets, Promoted Accounts and Promoted Trends. Twitter was founded by Jack Dorsey, Christopher Isaac Stone, Noah E. Glass, Jeremy LaTrasse, and Evan Williams on March 21, 2006 and is headquartered in San Francisco, CA.",
        ceo= "Jack Dorsey",
        employees= 4900,
        headquarters= "San Francisco, California",
        founded= 2006,
        market_cap= 23260000000,
        price_earning_ratio= 17.99,
        dividend_yield= 0,
        average_volume= 19150000)

    asset19 = Asset(name= "Slack",
        symbol= "WORK",
        description= "Slack Technologies, Inc. develops and publishes real-time collaboration applications and platforms. It provides engineering, sales, marketing, IT, project management and human resources solutions. The company was founded by Daniel Stewart Butterfield, Bradley J. Horowitz, Eric Costello, Callum James Henderson-Begg, and Serguei Mourachov in 2009 and is headquartered in San Francisco, CA.",
        ceo= "Daniel Stewart Butterfield",
        employees= 2045,
        headquarters= "San Francisco, California",
        founded= 2009,
        market_cap= 16150000000,
        price_earning_ratio= 0,
        dividend_yield= 0,
        average_volume= 15770000)

    asset20 = Asset(name= "Exxon Mobil",
        symbol= "XOM",
        description= "Exxon Mobil Corp. engages in the exploration, development, and distribution of oil, gas, and petroleum products. It operates through the following segments= Upstream, Downstream and Chemical. The Upstream segment produces crude oil and natural gas. The Downstream segment manufactures and trades petroleum products. The Chemical segment offers petrochemicals. The company was founded by John D. Rockefeller in 1882 and is headquartered in Irving, TX.",
        ceo= "Darren W. Woods",
        employees= 74900,
        headquarters= "Irving, Texas",
        founded= 1882,
        market_cap= 191710000000,
        price_earning_ratio= 15.78,
        dividend_yield= 8.29,
        average_volume= 28280000)

    asset21 = Asset(name= "Uber",
        symbol= "UBER",
        description= "Uber Technologies, Inc. operates as a technology platform for people and things mobility. The firm offers multi-modal people transportation, restaurant food delivery, and connecting freight carriers and shippers. It operates through the following segments= Rides, Eats, Freight, Other Bets and ATG and Other Technology Programs. The Rides segment refers to products that connect consumers with Rides Drivers who provide rides in a variety of vehicles, such as cars, auto rickshaws, motorbikes, minibuses, or taxis. The Eats segment allows consumers to search for and discover local restaurants, order a meal, and either pick-up at the restaurant or have the meal delivered. The Freight segment leverages proprietary technology, brand awareness, and experience revolutionizing industries to connect carriers with shippers on its platform, and gives carriers upfront, transparent pricing and the ability to book a shipment. The Other Bets segment consists of multiple investment stage offerings. The ATG and Other Technology Programs segment primarily responsible for the development and commercialization of autonomous vehicle and ridesharing technologies, as well as Uber Elevate. The company was founded by Oscar Salazar Gaitan, Travis Kalanick and Garrett Camp in 2009 and is headquartered in San Francisco, CA.",
        ceo= "Dara Khosrowshahi",
        employees= 26900,
        headquarters= "San Fransisco, California",
        founded= 2009,
        market_cap= 58300000000,
        price_earning_ratio= 0,
        dividend_yield= 0,
        average_volume= 45840000)

    asset22 = Asset(name= "Intel",
        symbol= "INTC",
        description= "Intel Corp. engages in the design, manufacture, and sale of computer products and technologies. It delivers computer, networking, data storage, and communications platforms. The firm operates through the following segments= Client Computing Group (CCG), Data Center Group (DCG), Internet of Things Group (IOTG), Non-Volatile Memory Solutions Group (NSG), Programmable Solutions (PSG), and All Other. The CCG segment consists of platforms designed for notebooks, 2-in-1 systems, desktops, tablets, phones, wireless and wired connectivity products, and mobile communication components. The DCG segment includes workload-optimized platforms and related products designed for enterprise, cloud, and communication infrastructure market. The IOTG segment offers compute solutions for targeted verticals and embedded applications for the retail, manufacturing, health care, energy, automotive, and government market segments. The NSG segment constitutes of NAND flash memory products primarily used in solid-state drives. The PSG segment contains programmable semiconductors and related products for a broad range of markets, including communications, data center, industrial, military, and automotive. The All Other segment consists of results from other non-reportable segment and corporate-related charges. The company was founded by Robert Norton Noyce and Gordon Earle Moore on July 18, 1968 and is headquartered in Santa Clara, CA.",
        ceo= "Robert Holmes Swan",
        employees= 110800,
        headquarters= "Santa Clara, California",
        founded= 1968,
        market_cap= 253700000000,
        price_earning_ratio= 11.29,
        dividend_yield= 2.26,
        average_volume= 20980000)

    asset23 = Asset(name= "NVIDIA",
        symbol= "NVDA",
        description= "NVIDIA Corp. engages in the design and manufacture of computer graphics processors, chipsets, and related multimedia software. It operates through the Graphics Processing Unit (GPU) and Tegra Processor segments. The GPU segment comprises of product brands, which aims specialized markets including GeForce for gamers; Quadro for designers; Tesla and DGX for AI data scientists and big data researchers; and GRID for cloud-based visual computing users. The Tegra Processor segment integrates an entire computer onto a single chip, and incorporates GPUs and multi-core CPUs to drive supercomputing for autonomous robots, drones, and cars, as well as for consoles and mobile gaming and entertainment devices. The company was founded by Jen-Hsun Huang, Chris A. Malachowsky, and Curtis R. Priem in January 1993 and is headquartered in Santa Clara, CA.",
        ceo= "Jen-Hsun Huang",
        employees= 13775,
        headquarters= "Santa Clara, California",
        founded= 1993,
        market_cap= 215300000000,
        price_earning_ratio= 75.07,
        dividend_yield= 0.19,
        average_volume= 13110000)

    asset24 = Asset(name= "British Petroleum",
        symbol= "BP",
        description= "BP Plc operates as an integrated oil and gas company. It operates through the following segments= Upstream, Downstream and Rosneft. The Upstream segment engages in the oil and natural gas exploration, field development and production, midstream transportation, storage and processing and marketing and trade of natural gas, including liquefied natural gas and power and natural gas liquids. The Downstream segment refines, manufactures, markets, transports, supplies, and trades crude oil, petroleum, petrochemicals products and related services to wholesale and retail customers. The Rosneft segment engages in investment activities. The company was founded by William Knox D'Arcy on April 14, 1909 and is headquartered in London, the United Kingdom.",
        ceo= "Bernard Looney",
        employees= 51230,
        headquarters= "London, Greater London",
        founded= 1909,
        market_cap= 78770000000,
        price_earning_ratio= 18.25,
        dividend_yield= 11.46,
        average_volume= 12030000)

    asset25 = Asset(name= "Walmart",
        symbol= "WMT",
        description= "Walmart, Inc. engages in retail and wholesale business. The Company offers an assortment of merchandise and services at everyday low prices. It operates through the following business segments= Walmart U.S., Walmart International, and Sam's Club. The Walmart U.S. segment operates as a merchandiser of consumer products, operating under the Walmart, Wal-Mart, and Walmart Neighborhood Market brands, as well as walmart.com and other eCommerce brands. The Walmart International segment manages supercenters, supermarkets, hypermarkets, warehouse clubs, and cash & carry outside of the United States. The Sam's Club segment comprises membership-only warehouse clubs and samsclubs.com. The company was founded by Samuel Moore Walton and James Lawrence Walton in 1945 and is headquartered in Bentonville, AR.",
        ceo= "C. Douglas McMillon",
        employees= 2200000,
        headquarters= "Bentonville, Arkansas",
        founded= 1945,
        market_cap= 361750000000,
        price_earning_ratio= 24.27,
        dividend_yield= 1.72,
        average_volume= 8710000)

    asset26 = Asset(name= "Pfizer",
        symbol= "PFE",
        description= "Pfizer Inc. engages in the discovery, development, and manufacture of healthcare products specializes in medicines, vaccine, and consumer healthcare. It operates through the Pfizer Innovative Health (IH) and Pfizer Essential Health (EH) segments. The IH segment focuses on the development and commercializing medicines and vaccines for internal medicine, oncology, inflammation and immunology, rate disease, and consumer healthcare. The EH segment is involved in development and supply of branded generics, generic sterile injectable products, biosimilars, and select branded products including anti-infectives. The company was founded by Charles Pfizer Sr. and Charles Erhart in 1849 and is headquartered in New York, NY.",
        ceo= "Albert Bourla",
        employees= 88300,
        headquarters= "New York, New York",
        founded= 1849,
        market_cap= 208310000000,
        price_earning_ratio= 133.33,
        dividend_yield= 4.04,
        average_volume= 19960000)

    asset27 = Asset(name= "IBM",
        symbol= "IBM",
        description= "International Business Machines Corporation, also called IBM, is an information technology company, which provides integrated solutions that leverage information technology and knowledge of business processes. It operates through the following segments= Cloud & Cognitive Software, Global Business Services, Global Technology Services, Systems, and Global Financing. The Cloud & Cognitive Software segment provides integrated and secure cloud, data and solutions to the clients. The Global Business Services segment provides clients with consulting, application management and global process services. The Global Technology Services segment provides comprehensive IT infrastructure and platform services that create business value for clients. The Systems segment provides clients with innovative infrastructure platforms to help meet the requirements of hybrid cloud and enterprise AI workload. The Global Financing segment encompasses two primary businesses= financing, primarily conducted through IBM Credit LLC, and remanufacturing and remarketing. The company was founded by Charles Ranlett Flint and Thomas J. Watson Sr. on June 16, 1911 and is headquartered in Armonk, NY.",
        ceo= "Arvind Krishna",
        employees= 383800,
        headquarters= "Armonk, New York",
        founded= 1911,
        market_cap= 105120000000,
        price_earning_ratio= 11.80,
        dividend_yield= 5.37,
        average_volume= 4370000)

    asset28 = Asset(name= "Johnson & Johnson",
        symbol= "JNJ",
        description= "Johnson & Johnson is a holding company, which engages in the research and development, manufacture and sale of products in the health care field. It operates through the following segments= Consumer, Pharmaceutical, and Medical Devices. The Consumer segment includes products used in the baby care, oral care, beauty, over-the-counter pharmaceutical, women's health, and wound care markets. The Pharmaceutical segment focuses on therapeutic areas such as immunology, infectious diseases ad vaccines, neuroscience, oncology, cardiovascular and metabolism, and pulmonary hypertension. The Medical Devices segment offers products used in the orthopedic, surgery, cardiovascular, diabetes care, and eye health fields. The company was founded by Robert Wood Johnson I, James Wood Johnson and Edward Mead Johnson Sr. in 1886 and is headquartered in New Brunswick, NJ.",
        ceo= "Alex Gorsky",
        employees= 132200,
        headquarters= "New Brunswick, New Jersey",
        founded= 1887,
        market_cap= 380360000000,
        price_earning_ratio= 22.88,
        dividend_yield= 2.74,
        average_volume= 6890000)

    asset29 = Asset(name= "Anheuser Busch InBev",
        symbol= "BUD",
        description= "Anheuser-Busch InBev SA/NV operates as a holding company, which engages in the manufacture and distribution of alcoholic and non-alcoholic beverages. It operates through the following geographical segments= North America, Latin America West, Latin America North, Latin America South, EMEA, Asia Pacific and Global Export and Holding Companies. The Global Export and Holding Companies segment includes the global headquarters and the export businesses in other countries. Its brands include Budweiser, Corona and Stella Artois; multi-country brands Beck's, Castle, Castle Lite, Hoegaarden and Leffe; and local champions, such as Aguila, Antarctica, Bud Light, Brahma, Cass, Chernigivske, Cristal, Harbin, Jupiler, Klinskoye, Michelob Ultra, Modelo Especial, Quilmes, Victoria, Sedrin, Sibirskaya Korona, and Skol. The company was founded on August 2, 1977 and is headquartered in Leuven, Belgium.",
        ceo= "Carlos Alves de Brito",
        employees= 171915,
        headquarters= "Leuven, Brussels Region",
        founded= 1977,
        market_cap= 66810000000,
        price_earning_ratio= 8.90,
        dividend_yield= 3.53,
        average_volume= 3080000)

    asset30 = Asset(name= "PepsiCo",
        symbol= "PEP",
        description= "PepsiCo, Inc. engages in the manufacture, marketing, distribution and sale of beverages, food, and snacks. It is a food and beverage company with a complementary portfolio of brands, including Frito-Lay, Gatorade, Pepsi-Cola, Quaker, and Tropicana. It operates through the following business segments= Frito-Lay North America; Quaker Foods North America; North America Beverages; Latin America; Europe Sub-Saharan Africa; and Asia, Middle East, and North Africa. The Frito-Lay North America segment markets, distributes, and sells snack foods under the Lay's, Doritos, Cheetos, Tostitos, Fritos, Ruffles, and Santitas brands. The Quaker Foods North America segment includes cereals, rice, and pasta under the Quaker, Aunt Jemima, Quaker Chewy, Cap'n Crunch, Life, and Rice-A-Roni brands. The North America Beverages segment consists of beverage concentrates, fountain syrups, and finished goods under various beverage brands such as Pepsi, Gatorade, Mountain Dew, Diet Pepsi, Aquafina, Diet Mountain Dew, Tropicana Pure Premium, Sierra Mist, and Mug. The Latin America segment covers beverage, food, and snack businesses in Latin America region. The Europe Sub-Saharan Africa segment comprises of beverage, food, and snack goods in Europe and Sub-Saharan Africa regions. The Asia, Middle East, and North Africa segment offers snack food products under the Lay's, Kurkure, Chipsy, Doritos, Cheetos, and Crunchy brands. The company was founded by Donald M. Kendall, Sr. and Herman W. Lay in 1965 and is headquartered in Purchase, NY.",
        ceo= "Ramon Luis Laguarta",
        employees= 267000,
        headquarters= "Purchase, New York",
        founded= 1965,
        market_cap= 181040000000,
        price_earning_ratio= 25.27,
        dividend_yield= 3.14,
        average_volume= 7010000)

    asset31 = Asset(name= "Costco",
        symbol= "COST",
        description= "Costco Wholesale Corp. engages in the operation of membership warehouses. Its product categories include food and sundries, hardlines, fresh foods, softlines, and ancillary. It operates through the following segments= Unites States Operations, Canadian Operations, and Other International Operations. The company was founded by James D. Sinegal and Jeffrey H. Brotman in 1983 and is headquartered in Issaquah, WA.",
        ceo= "Walter Craig Jelinek",
        employees= 254000,
        headquarters= "Issaquah, Washington",
        founded= 1983,
        market_cap= 133550000000,
        price_earning_ratio= 35.42,
        dividend_yield= 0.93,
        average_volume= 3050000)

    asset32 = Asset(name= "Kraft Foods",
        symbol= "KHC",
        description= "The Kraft Heinz Co. engages in the manufacture and market of food and beverage products. It operates through the following geographical segments= United States, Canada, EMEA, and Rest of the World. The Rest of the World segment is comprised of the Latin America and Asia Pacific segments. Its products include condiments and sauces, cheese and dairy, ambient meals, frozen and chilled meals, and for infant and nutrition. The company was founded on July 2, 2015 and is headquartered in Pittsburgh, PA.",
        ceo= "Miguel Patricio",
        employees= 37000,
        headquarters= "Pittsburgh, Pennsylvania",
        founded= 1909,
        market_cap= 36590000000,
        price_earning_ratio= 19.05,
        dividend_yield= 5.39,
        average_volume= 5690000)

    asset33 = Asset(name= "Lockheed",
        symbol= "LMT",
        description= "Lockheed Martin Corp. operates as a global security and aerospace company, which engages in the research, design, development, manufacture, integration, and sustainment of technology systems, products, and services. It operates through the following business segments= Aeronautics, Missiles and Fire Control (MFC), Rotary and Mission Systems (RMS) and Space. The Aeronautics segment researches, designs, develops, manufactures, integrates, sustains, supports, and upgrades advanced military aircraft, including combat and air mobility aircraft, unmanned air vehicles, and related technologies. The MFC segment provides air and missile defence systems; tactical missiles and air-to-ground precision strike weapon systems; logistics; fire control systems; mission operations support, readiness, engineering support and integration services; manned and unmanned ground vehicles; and energy management solutions. The RMS segment offers design, manufacture, service, and support for a variety of military and commercial helicopters; ship and submarine mission and combat systems; mission systems and sensors for rotary and fixed-wing aircraft; sea and land-based missile defence systems; radar systems; the Littoral Combat Ship; simulation and training services; and unmanned systems and technologies. The Space segment comprises of the research and development, design, engineering and production of satellites, strategic, and defensive missile systems and space transportation systems. The company was founded in 1961 and is headquartered in Bethesda, MD.",
        ceo= "Marillyn A. Hewson",
        employees= 110000,
        headquarters= "Bethesda, Maryland",
        founded= 1961,
        market_cap= 103480000000,
        price_earning_ratio= 16.74,
        dividend_yield= 2.65,
        average_volume= 1440000)

    asset34 = Asset(name= "Oracle ",
        symbol= "ORCL",
        description= "Oracle Corp. engages in the provision of products and services that address all aspects of corporate information technology environments. It operates through the following business segments= Cloud and License, Hardware, and Services. The Cloud and License segment markets, sells, and delivers applications, platform, and infrastructure technologies. The Hardware segment provides hardware products and hardware-related software products including Oracle Engineered Systems, servers, storage, industry-specific hardware, operating systems, virtualization, management and other hardware related software, and related hardware support. The Services segment offers consulting, advanced support, and education services. The company was founded by Lawrence Joseph Ellison, Robert Nimrod Miner and Edward A. Oates on June 16, 1977 and is headquartered in Redwood City, CA.",
        ceo= "Safra Ada Catz",
        employees= 136000,
        headquarters= "Redwood City, California",
        founded= 1977,
        market_cap= 165940000000,
        price_earning_ratio= 16.44,
        dividend_yield= 1.81,
        average_volume= 12320000)

    asset35 = Asset(name= "Qualcomm",
        symbol= "QCOM",
        description= "QUALCOMM, Inc. engages in the development, design, and provision of digital telecommunications products and services. It operates through the following segments= Qualcomm CDMA Technologies (QCT), Qualcomm Technology Licensing (QTL), and Qualcomm Strategic Initiatives (QSI). The QCT segment develops and supplies integrated circuits and system software based on technologies for the use in voice and data communications, networking, application processing, multimedia, and global positioning system products. The QTL segment grants licenses and provides rights to use portions of the firm's intellectual property portfolio. The QSI segment focuses on opening new or expanding opportunities for its technologies and supporting the design and introduction of new products and services for voice and data communications. The company was founded by Franklin P. Antonio, Adelia A. Coffman, Andrew Cohen, Klein Gilhousen, Irwin Mark Jacobs, Andrew J. Viterbi, and Harvey P. White in July 1985 and is headquartered in San Diego, CA.",
        ceo= "Steven M. Mollenkopt",
        employees= 37000,
        headquarters= "San Diego, California",
        founded= 1985,
        market_cap= 88530000000,
        price_earning_ratio= 23.13,
        dividend_yield= 3.33,
        average_volume= 10940000)

    asset36 = Asset(name= "Royal Caribbean",
        symbol= "RCL",
        description= "Royal Caribbean Cruises Ltd. operates as a global cruise vacation company. It operates global cruise brands= Royal Caribbean International, Celebrity Cruises, Azamara and Silversea Cruises. The firm also holds interest in TUI Cruises, Pullmantur and SkySea Cruises brands. The company was founded in 1968 and is headquartered in Miami, FL.",
        ceo= "Richard D. Fain",
        employees= 85400,
        headquarters= "Miani, Florida",
        founded= 1968,
        market_cap= 9020000000,
        price_earning_ratio= 51.10,
        dividend_yield= 7.66,
        average_volume= 19660000)

    asset37 = Asset(name= "Verizon",
        symbol= "VZ",
        description= "Verizon Communications, also called Verizon, is a holding company, which engages in the provision of communications, information, and entertainment products and services to consumers, businesses, and governmental agencies. It operates through the Verizon Consumer Group (Consumer) and Verizon Business Group (Business) segments. The Consumer segment provides consumer-focused wireless and wire line communications services and products. The Business segment offers wireless and wire line communications services and products; video and data services; corporate networking solutions; security and managed network services; local and long distance voice services; and network access to deliver various Internet of Things (IoT) services and products. The company was founded in 1983 and is headquartered in New York, NY.",
        ceo= "Hans Erik Gruber",
        employees= 135000,
        headquarters= "New York, New York",
        founded= 1983,
        market_cap= 223870000000,
        price_earning_ratio= 12.15,
        dividend_yield= 4.56,
        average_volume= 16610000)

    asset38 = Asset(name= "Xilinx",
        symbol= "XLNX",
        description= "Xilinx, Inc. engages in the design and development of programmable logic semiconductor devices and the related software design tools. It also provides design services, customer training, field engineering, and technical support. The company was founded by Ross Freeman, Bernard Vonderschmitt, and James V. Barnett in February 1984 and is headquartered in San Jose, CA.",
        ceo= "Victor Peng",
        employees= 4891,
        headquarters= "San Jose, California",
        founded= 1984,
        market_cap= 21060000000,
        price_earning_ratio= 28.06,
        dividend_yield= 1.74,
        average_volume= 2610000)

    asset39 = Asset(name= "YETI",
        symbol= "YETI",
        description= "YETI Holdings, Inc. engages in the design, marketing, and distribution of products for the outdoor and recreation market. Its products include coolers, drinkware, travel bags, backpacks, multipurpose buckets, outdoor chairs, blankets, dog bowls, apparel, and accessories. The company was founded by Roy J. Seiders and Ryan R. Seiders in 2006 and is headquartered in Austin, TX.",
        ceo= "Matthew j. Reintjes",
        employees= 790,
        headquarters= "Austin, Texas",
        founded= 2006,
        market_cap= 2650000000,
        price_earning_ratio= 45.80,
        dividend_yield= 0,
        average_volume= 3460000)



    db.session.add(asset1)
    db.session.add(asset2)
    db.session.add(asset3)
    db.session.add(asset4)
    db.session.add(asset5)
    db.session.add(asset6)
    db.session.add(asset7)
    db.session.add(asset8)
    db.session.add(asset9)
    db.session.add(asset10)
    db.session.add(asset11)
    db.session.add(asset12)
    db.session.add(asset13)
    db.session.add(asset14)
    db.session.add(asset15)
    db.session.add(asset16)
    db.session.add(asset17)
    db.session.add(asset18)
    db.session.add(asset19)
    db.session.add(asset20)
    db.session.add(asset21)
    db.session.add(asset22)
    db.session.add(asset23)
    db.session.add(asset24)
    db.session.add(asset25)
    db.session.add(asset26)
    db.session.add(asset27)
    db.session.add(asset28)
    db.session.add(asset29)
    db.session.add(asset30)
    db.session.add(asset31)
    db.session.add(asset32)
    db.session.add(asset33)
    db.session.add(asset34)
    db.session.add(asset35)
    db.session.add(asset36)
    db.session.add(asset37)
    db.session.add(asset38)
    db.session.add(asset39)


    db.session.commit()


def undo_assets():
    db.session.execute('TRUNCATE assets CASCADE;')
    db.session.commit()
