"""empty message

Revision ID: 944308be722c
Revises: 107940652962
Create Date: 2021-05-24 16:37:35.871902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944308be722c'
down_revision = '107940652962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'created_at')
    # ### end Alembic commands ###
