"""empty message

Revision ID: 9c2091134372
Revises: 87d391e2daab
Create Date: 2021-05-25 19:07:12.574707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2091134372'
down_revision = '87d391e2daab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('price_per_share', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'price_per_share')
    # ### end Alembic commands ###
