"""empty message

Revision ID: 107940652962
Revises: 
Create Date: 2021-05-23 19:13:04.316296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107940652962'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('ceo', sa.String(), nullable=False),
    sa.Column('employees', sa.Integer(), nullable=False),
    sa.Column('headquarters', sa.String(), nullable=False),
    sa.Column('founded', sa.Integer(), nullable=False),
    sa.Column('market_cap', sa.BigInteger(), nullable=False),
    sa.Column('price_earning_ratio', sa.Integer(), nullable=False),
    sa.Column('dividend_yield', sa.Integer(), nullable=False),
    sa.Column('average_volume', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('buying_power', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('share_quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_share', sa.Integer(), nullable=False),
    sa.Column('buy_sell', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('users')
    op.drop_table('assets')
    # ### end Alembic commands ###
