"""empty message

Revision ID: 81522004dfd5
Revises: 66223a76224b
Create Date: 2021-05-23 17:03:41.763187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81522004dfd5'
down_revision = '66223a76224b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('buying_power', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'buying_power')
    # ### end Alembic commands ###
